#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=8

PROFILE_NAME="${XIAOD_PROFILE:-media-transcriber}"
PROFILE_HOME="${XIAOD_PROFILE_HOME:-${HERMES_HOME:-$HOME/.hermes}/profiles/$PROFILE_NAME}"
ENV_FILE="${XIAOD_ENV_FILE:-$PROFILE_HOME/.env}"
HERMES_BIN="${XIAOD_HERMES_BIN:-$(command -v hermes || true)}"
LARK_BIN="${XIAOD_LARK_CLI:-$(command -v lark-cli-user || command -v lark-cli || true)}"
EXPECTED_BOT_NAME="小D-链接转录助手"
WIKI_SPACE_NAME="音视频转录整理"

[[ -n "$HERMES_BIN" ]] || { warn "未找到 Hermes CLI，请先安装 Hermes。"; exit 1; }
mkdir -p "$PROFILE_HOME"

env_has_value() {
  [[ -f "$ENV_FILE" ]] && grep -Eq "^${1}=.+" "$ENV_FILE"
}

pairing_count() {
  /usr/bin/python3 - "$PROFILE_HOME/platforms/pairing/feishu-approved.json" <<'PY'
import json, sys
try:
    value = json.load(open(sys.argv[1], encoding="utf-8"))
except Exception:
    print(0)
else:
    print(len(value) if isinstance(value, (dict, list)) else 0)
PY
}

wiki_count() {
  "$LARK_BIN" wiki +space-list --as user --page-all --json \
    --jq '[.. | objects | select(.name? == "音视频转录整理")] | length' \
    2>/dev/null | tail -n 1
}

banner "小D-链接转录助手 · 首次配置"

stage "模型服务"
say "在 Hermes 向导中选择自己的模型服务，并在本机完成凭据配置。"
note "输入内容由 Hermes 保存；本安装包不会读取或复制。"
"$HERMES_BIN" --profile "$PROFILE_NAME" setup

stage "部署飞书机器人"
say "Hermes 可以扫码创建并绑定飞书机器人。"
step "在平台列表选择 Feishu / Lark。"
step "优先选择扫码自动创建，使用飞书手机端确认。"
step "私聊权限选择 DM pairing；群聊选择仅在 @ 时回复。"
"$HERMES_BIN" --profile "$PROFILE_NAME" gateway setup
if ! env_has_value FEISHU_APP_ID || ! env_has_value FEISHU_APP_SECRET; then
  warn "没有检测到飞书机器人配置。请重新运行本向导完成该阶段。"
  exit 1
fi

stage "修改并发布机器人名称"
say "飞书机器人必须使用统一名称：$EXPECTED_BOT_NAME"
open_url "https://open.feishu.cn/app"
step "打开刚才创建的应用，进入基础信息或机器人配置。"
step "把应用/机器人名称改为“$EXPECTED_BOT_NAME”并保存。"
step "如果页面要求创建版本或发布变更，请完成发布后再继续。"
pause "完成改名和发布后按 Enter"
if ! confirm "你已在飞书后台确认生效名称为“$EXPECTED_BOT_NAME”吗？"; then
  warn "名称未确认，配置暂停。完成后重新运行 xiaod-setup。"
  exit 1
fi
write_env XIAOD_FEISHU_BOT_NAME "$EXPECTED_BOT_NAME"

stage "启动消息网关"
say "安装开机自启的 Hermes 网关，让飞书消息能到达本机小D。"
"$HERMES_BIN" --profile "$PROFILE_NAME" gateway install --force --start-now --start-on-login
if ! "$HERMES_BIN" --profile "$PROFILE_NAME" gateway status --deep; then
  warn "网关没有正常运行。请处理上方错误后重新运行 xiaod-setup。"
  exit 1
fi

stage "飞书私聊配对"
if [[ "$(pairing_count)" -gt 0 ]]; then
  say "已存在飞书配对，跳过。"
else
  step "在飞书中搜索“$EXPECTED_BOT_NAME”，发送“你好”。"
  step "机器人会回复一次性配对码。"
  ask PAIRING_CODE "粘贴配对码："
  if [[ ! "$PAIRING_CODE" =~ ^[A-Za-z0-9]{6,12}$ ]]; then
    warn "配对码格式不正确。"
    exit 1
  fi
  "$HERMES_BIN" --profile "$PROFILE_NAME" pairing approve feishu "$PAIRING_CODE"
fi
[[ "$(pairing_count)" -gt 0 ]] || { warn "飞书配对尚未完成。"; exit 1; }

stage "飞书 CLI 用户授权"
if [[ -z "$LARK_BIN" ]]; then
  warn "未找到 lark-cli。请先安装飞书 CLI，再重新运行 xiaod-setup。"
  exit 1
fi
if ! "$LARK_BIN" auth status --json --verify >/dev/null 2>&1; then
  say "接下来只授权文档、云盘、知识库和转录读取所需能力。"
  "$LARK_BIN" auth login --domain docs,markdown,wiki,drive,minutes,note --recommend
fi
"$LARK_BIN" config default-as user
"$LARK_BIN" whoami --as user >/dev/null

stage "目标知识库"
say "小D默认把成稿交付到“$WIKI_SPACE_NAME”。"
SPACE_COUNT="$(wiki_count || echo -1)"
if [[ "$SPACE_COUNT" == "0" ]]; then
  if confirm "当前账号看不到该知识库，是否现在创建？"; then
    "$LARK_BIN" wiki +space-create --as user --name "$WIKI_SPACE_NAME" \
      --description "小D整理后的音视频与链接文档" >/dev/null
    SPACE_COUNT="$(wiki_count || echo -1)"
  fi
fi
if [[ "$SPACE_COUNT" != "1" ]]; then
  warn "必须恰好有一个同名知识库；当前匹配数量：$SPACE_COUNT。"
  warn "请处理权限、名称或重名问题后重新运行 xiaod-setup。"
  exit 1
fi
write_env XIAOD_WIKI_SPACE_NAME "$WIKI_SPACE_NAME"

stage "最终验收"
say "运行端到端检查；任何失败项都不会被当作安装完成。"
if command -v xiaod-doctor >/dev/null 2>&1; then
  xiaod-doctor
else
  /usr/bin/python3 "$PROFILE_HOME/scripts/doctor.py" --profile "$PROFILE_NAME"
fi

finish
